// Generated by ts-to-zod
import { z } from 'zod'

export const assetPropertiesSchema = z.object({
  id: z.string(),
})

export const conversionPropertiesSchema = z.object({
  output_file_format: z.string().nullable(),
  output_file_type: z.string().nullable(),
})

export const filePropertiesSchema = z.object({
  file_type: z.string(),
  format: z.string(),
  size_in_bytes: z.number(),
})

export const intendedUsePropertiesSchema = z.object({
  value: z.string().nullable(),
})

export const userPropertiesSchema = z.object({
  id: z.string().nullable(),
})

export const shareAssetEventSchema = z.object({
  asset_properties: assetPropertiesSchema,
  referrer: z.string(),
  timestamp: z.date(),
  user_properties: userPropertiesSchema,
})

export const viewAssetEventSchema = z.object({
  asset_properties: assetPropertiesSchema,
  file_properties: filePropertiesSchema,
  intended_use_properties: intendedUsePropertiesSchema,
  referrer: z.string(),
  timestamp: z.date(),
  user_properties: userPropertiesSchema,
})

export const downloadAssetEventSchema = z.object({
  asset_properties: assetPropertiesSchema,
  conversion_properties: conversionPropertiesSchema,
  file_properties: filePropertiesSchema,
  intended_use_properties: intendedUsePropertiesSchema,
  referrer: z.string(),
  timestamp: z.date(),
  user_properties: userPropertiesSchema,
})

export const listAssetSharesResponseSchema = z.object({
  items: z.array(shareAssetEventSchema),
  pagination_token: z.string().nullable(),
  total_count: z.number(),
})

export const listAssetViewsResponseSchema = z.object({
  items: z.array(viewAssetEventSchema),
  pagination_token: z.string().nullable(),
  total_count: z.number(),
})

export const listAssetDownloadsResponseSchema = z.object({
  items: z.array(downloadAssetEventSchema),
  pagination_token: z.string().nullable(),
  total_count: z.number(),
})
