// Generated by ts-to-zod
import { z } from 'zod'

export const attributeSchema = z.object({
  attribute_group: z
    .object({
      attribute_group_id: z.string(),
      name: z.string(),
    })
    .nullable(),
  attribute_id: z.string(),
  import_only: z.boolean(),
  name: z.string(),
  type: z.string(),
})

export const listAttributeVocabularyResultSchema = z.object({
  vocabulary: z.array(z.string()),
})

export const listAttributesResultSchema = z.object({
  item_type: z.string(),
  items: z.array(attributeSchema),
  limit: z.number(),
  offset: z.number(),
  total_count: z.number(),
})
