// Generated by ts-to-zod
import { z } from 'zod'
import { type CategoryV1 } from './../apis/categories/responses'

export const categoryV1Schema: z.ZodSchema<CategoryV1> = z.lazy(() =>
  z.object({
    children: z.array(categoryV1Schema),
    id: z.number(),
    title: z.string(),
    uuid: z.string(),
  })
)

export const categoryTreeResultSchema = z.object({
  categories: z.array(categoryV1Schema),
  parentCategory: z.null(),
})

export const categoryV2Schema = z.object({
  _links: z.object({
    assets: z.string(),
    categories: z.string(),
  }),
  id: z.string(),
  name: z.string(),
  parts: z.array(z.string()),
  path: z.string(),
})

export const createEditCategoryResultSchema = z.object({
  children: z.array(categoryV1Schema),
  id: z.number(),
  title: z.string(),
  uuid: z.string(),
})

export const listCategoriesResultSchema = z.object({
  item_type: z.string(),
  items: z.array(categoryV2Schema),
  total_count: z.number(),
})
