// Generated by ts-to-zod
import { z } from 'zod'

export const listCollectionsResultSchema = z.object({
  item_type: z.string(),
  items: z.array(
    z.object({
      _links: z.object({
        assets: z.string().optional(),
      }),
      id: z.string(),
      title: z.string(),
      total_items: z.number(),
      type: z.string(),
    })
  ),
  limit: z.number(),
  offset: z.number(),
  total_count: z.number(),
})

const collectionTypeSchema = z.any()

export const createCollectionResultSchema = z.object({
  assets: z.array(
    z.object({
      uuid: z.string(),
    })
  ),
  assetsAddedCount: z.number(),
  description: z.string(),
  name: z.string(),
  numResults: z.number(),
  type: collectionTypeSchema,
  uuid: z.string(),
})
