// Generated by ts-to-zod
import { z } from 'zod'

export const getUsageResultSchema = z.object({
  report_end_timestamp: z.date(),
  report_start_timestamp: z.date(),
  request_count: z.number(),
})
