// Generated by ts-to-zod
import { z } from 'zod'

export const getUserResultSchema = z.object({
  city: z.string().nullable(),
  company: z.string().nullable(),
  country: z.string().nullable(),
  email: z.string(),
  first_name: z.string(),
  id: z.string(),
  last_name: z.string(),
  phone: z.string().nullable(),
  postal_code: z.string().nullable(),
  state_or_province: z.string().nullable(),
  street_address: z.string().nullable(),
  title: z.string().nullable(),
  username: z.string(),
  uuid: z.string(),
})

export const contactFieldSchema = z.object({
  required: z.boolean(),
  value: z.string().nullable(),
})

export const userSchema = getUserResultSchema

export const getContactResultSchema = z.object({
  fields: z.object({
    city: contactFieldSchema,
    company: contactFieldSchema,
    country: contactFieldSchema,
    email: contactFieldSchema,
    firstName: contactFieldSchema,
    lastName: contactFieldSchema,
    phone: contactFieldSchema,
    postalCode: contactFieldSchema,
    stateOrProvince: contactFieldSchema,
    streetAddress: contactFieldSchema,
  }),
  uuid: z.string(),
})

export const contactSchema = getContactResultSchema
